version: '3.9'

services:

  gitea-server:
    build: ./gitea-server
    container_name: gitea-server
    volumes:
      - ./.data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7301:3000"
      - "7302:22"

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server

  config-server:
    build: ./config-server
    container_name: config-server



