version: '3.9'

services:

  gitea-server:
    build: ./gitea-server
    container_name: gitea-server
    volumes:
      - ./.data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7301:3000"
      - "7302:7302" # Setup of gitea is done with 7302 as ssh

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server

  config-server:
    build: ./config-server
    container_name: config-server

  demo-helper:
    build: ./demo-helper
    container_name: demo-helper
    environment:
      - "GITEA_HOST=gitea-server"
      - "GITEA_ADMIN_USERNAME=demoadmin"
      - "GITEA_ADMIN_PASSWORD=demo#123"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/root
      - ./demo-helper/scripts:/scripts             #TODO: Temporary code


