server:
  port: ${PORT:8312}

spring:
  application.name: config-server
  output.ansi.enabled: ALWAYS
  cloud.config.server.git:
    search-paths: '{application}'
    uri: file://///Users/mafzal/source/demo-school